# Generated by Django 4.2.16 on 2024-09-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTech_App', '0002_marksheet_delete_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
            ],
        ),
        migrations.DeleteModel(
            name='Marksheet',
        ),
    ]
