# Generated by Django 4.2.16 on 2024-09-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTech_App', '0003_certificate_delete_marksheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_file',
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
