# Generated by Django 4.2.16 on 2024-09-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTech_App', '0004_remove_certificate_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='offer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
