# Generated by Django 4.2.11 on 2024-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTech_App', '0005_certificate_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(null=True, upload_to='certificates/'),
        ),
    ]
