# Generated by Django 4.2.16 on 2024-09-24 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTech_App', '0007_alter_certificate_certificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issued',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
