# Generated by Django 4.2.16 on 2024-09-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTech_App', '0008_alter_certificate_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issued',
            field=models.DateField(null=True),
        ),
    ]
