# Generated by Django 4.2.16 on 2024-09-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTech_App', '0009_alter_certificate_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
